# 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np

# 2. Reading a local CSV File

In [2]:
df = pd.read_csv('customer.csv')
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

# 3. Selecting Column for train_test_split

In [3]:
df=df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

# 4. Apply Train-Test-Split

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.25)

In [5]:
X_train.head()

     review education
30  Average        UG
47     Good        PG
13  Average    School
26     Poor        PG
32  Average        UG

In [6]:
X_test.head()

     review education
39     Poor        PG
2      Good        PG
46     Poor        PG
12     Poor    School
20  Average    School

# 5. Apply Ordinal Encoding

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])
oe=oe.fit(X_train)               # Fit the Training Dataset using Ordinal Encoding

In [9]:
oe.get_params()

{'categories': [['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']],
 'dtype': numpy.float64,
 'encoded_missing_value': nan,
 'handle_unknown': 'error',
 'max_categories': None,
 'min_frequency': None,
 'unknown_value': None}

# 6. Transform the Training and Testing Dataset using Ordinal Encoding

In [10]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [11]:
X_train

array([[1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [0., 0.],
       [2., 2.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# 7. Apply Label Encoder for the Output Category

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()

In [15]:
le.fit(y_train)

LabelEncoder()

In [16]:
le.get_params()

{}

In [17]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [18]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [19]:
y_test

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1])